# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 96baae221f2cf8faf01ddeecdda13ea38cd031e3522eac81d0973d76fb295bc14891bb572b372108c58be62732748bde1d372b987ad7ed250510cf58c7f10e64

test:
  secret_key_base: 64a6a82d6300dc375868c48d7ba8d3d617d7f1a173d56c64d34754d80c1a85e8d9d5e01573832452dfd1bf0b432dca8a78565f3d2bd8a9847371b7af30456ab2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
